mikedilger/gossip

src/feed.rs

Before: ![2023-01-13-155453_939x311_scrot](https://user-images.githubusercontent.com/1653275/212399608-cab6ee5d-e72c-4aaa-aa2b-bcfcf37963e5.png)
After: (couldn't test)

Filter out messages from the future

---

src/overlord/mod.rs
src/ui/feed.rs

eliminate all forms of "p" tag duplication

---

src/ui/relays.rs

When adding a relay, update the GLOBALS.relay.
Separate write relays from other known relays.
Removed some old commented code.

Relay page changes

---

src/main.rs
src/overlord/mod.rs
src/people.rs
src/tags.rs
src/ui/feed.rs
src/ui/mod.rs

instead of inserting a "#[index]" string.
includes a new file `tags.rs` with useful functions.

insert and parse npub keys into and from text content.

---

src/overlord/mod.rs
src/tags.rs
src/ui/feed.rs

(adding "mention" "e" tags along with a reference to them in `.content`).
does it just like the npub-parsing thing, now with note1 parsing.
also refactors some of the previous PR that added npub parsing and fixes a bug that caused mentions to not be recognized some times.

Allow mentions/quotes to be made

---

src/ui/help/mod.rs

Looks like you added nprofile support so don't need the unsupported note in help.
#116

remove nprofile unsupported note in help

---

src/globals.rs
src/ui/feed/mod.rs

Show a filled version of the like icon, if the current user reacted to a post.

Reactions: Show filled icon if user already reacted

---

Cargo.lock
Cargo.toml

fixing clipboard for wayland #186

---

src/ui/feed/mod.rs

Apply the logic to highlight the original poster if the repost is without comment.
It's not pixel perfect, the top bar and the bottom icons require a full revision but it's a step on the right direction.

Resize the avatar on plain repost without comment

---

README.md

Just discovered this file, contains a lot of interesting points and the cargo clippy / fmt PR requirements.
Could be useful to make it more visible; I  added it now to the Status paragraph ma perhaps a specific Contribute one could be better.

Link DEVELOPING.md in the README

---

src/overlord/minion/handle_websocket.rs

Separate log levels for accepted vs rejected events.

Log relay response as warn if event was rejected

---

src/ui/feed/note/mod.rs
src/ui/theme/default.rs
src/ui/theme/mod.rs

A little update using lines with dynamic height, waiting the full threads ui.
Left original, right updated.

Update the Default theme: indentation and padding

---

src/db/mod.rs
src/db/sql/schema27.sql

Before, the main feed would take ~13s to load.
After, it takes 1-2s.

Add SQL indices to speed up initial load

---

src/db/mod.rs

I had to do something similar to this on another r2d2 sqlite project. Seems to cut down significantly on the lock errors I was seeing locally.
Fixes https://github.com/mikedilger/gossip/issues/299

Attempt to solve DB locking problem

---

src/settings.rs
src/ui/feed/note/content.rs
src/ui/feed/note/mod.rs
src/ui/settings.rs

- setting saving, on by default
- cargo fmt and clippy ran for new lines

Add setting to render the first mention of a post as a repost

---

src/ui/feed/mod.rs
src/ui/feed/note/content.rs
src/ui/feed/note/mod.rs
src/ui/feed/post.rs
src/ui/theme/classic.rs
src/ui/theme/default.rs
src/ui/theme/mod.rs
src/ui/theme/roundy.rs

Should support design as laid out in #305

Restructure note rendering to support nested reposts

---

src/ui/feed/note/mod.rs
src/ui/theme/classic.rs
src/ui/theme/default.rs
src/ui/theme/roundy.rs

It will not show if there is a content warning or in JSON and QR views.

Fix position of subject line. 

---

src/ui/feed/note/mod.rs

Increase subject line spacing to match blank lines

---

src/events.rs
src/ui/feed/note/content.rs
src/ui/feed/note/mod.rs
src/ui/feed/note/notedata.rs

since the event cache is already queries in render_content() it's a bug to exclude uncached mentions since notedata is now cached

Fix uncached mentioned events resulting in empty repost

---

Cargo.toml
src/media.rs
src/ui/feed/note/content.rs
src/ui/mod.rs

strip arguments when evaluating file endings, fixes #362

Fix media urls with arguments

---

src/settings.rs
src/ui/mod.rs
src/ui/settings.rs

Add setting "feed_direction_reverse_chronological: bool"

---

src/ui/theme/default.rs

* Fix hue rotate calculation
* Increase warnings labels contrast

Colors fix and optimization - Default theme

---

src/comms.rs
src/feed.rs
src/globals.rs
src/overlord/minion/mod.rs
src/overlord/mod.rs
src/settings.rs
src/ui/components/mod.rs
src/ui/feed/mod.rs
src/ui/feed/note/content.rs
src/ui/feed/post.rs
src/ui/help/mod.rs
src/ui/mod.rs
src/ui/people/mod.rs
src/ui/relays/mod.rs
src/ui/settings.rs
src/ui/theme/default.rs
src/ui/theme/mod.rs
src/ui/you/mod.rs

Merged version of @dtonon and my work

Additional UI work for side-menu

---

src/ui/feed/note/content.rs

also try to parse them as bech32 but print a warning.
I think it would be better to catch this in the JSON parser, but not sure how to fix that.

Handle invalid hex keys without crashing, 

---

src/ui/mod.rs

Just a small touch up I noticed

Dont show 'View Their Posts' when on the persons feed

---

src/ui/feed/note/mod.rs
src/ui/mod.rs

I updated the njump endpoint and added a "copy web link" for the profile.

njump update

---

src/ui/relays/mine.rs

Fix item M3 from todo list: #477

my relays: fix duplicate search field

---

gossip-bin/build.rs
gossip-lib/build.rs

Separate build scripts for bin and library to fix macos ffmpeg library linking

Fix macOS linking

---

gossip-bin/src/ui/feed/note/mod.rs
gossip-bin/src/ui/mod.rs
gossip-bin/src/ui/people/followed.rs
gossip-bin/src/ui/people/muted.rs
gossip-bin/src/ui/people/person.rs
gossip-bin/src/ui/search.rs

Just a quick restyling, waiting #508.
Before:
<br/>
After:

Restyle a little the profile page

---

gossip-bin/src/ui/feed/note/mod.rs
gossip-bin/src/ui/theme/default.rs

Reduced the size and lowered the color brightness of the note labels, e.g.:

Review the color/size of note labels

---

gossip-bin/src/ui/mod.rs
gossip-bin/src/ui/people/lists.rs
gossip-bin/src/ui/relays/active.rs
gossip-bin/src/ui/relays/coverage.rs
gossip-bin/src/ui/relays/known.rs
gossip-bin/src/ui/relays/mine.rs
gossip-bin/src/ui/widgets/mod.rs

Same style as DM-chat-list page

Re-style "PeopleList" page

---

gossip-bin/src/ui/feed/post.rs
gossip-bin/src/ui/mod.rs
gossip-bin/src/ui/people/list.rs
gossip-bin/src/ui/people/lists.rs
gossip-bin/src/ui/relays/mod.rs
gossip-bin/src/ui/widgets/more_menu.rs

Put login into popup frame to center it:
Unified "more menu" for lists between all lists and individual lists view.

unify more menu for lists

---

gossip-bin/src/ui/mod.rs
gossip-bin/src/ui/theme/default.rs
gossip-bin/src/ui/theme/mod.rs
gossip-bin/src/ui/widgets/mod.rs
gossip-bin/src/ui/widgets/textedit.rs
gossip-bin/src/ui/wizard/follow_people.rs
gossip-bin/src/ui/wizard/import_private_key.rs
gossip-bin/src/ui/wizard/import_public_key.rs
gossip-bin/src/ui/wizard/read_nostr_config.rs
gossip-bin/src/ui/wizard/setup_metadata.rs
gossip-bin/src/ui/wizard/setup_relays.rs

Feature/style login screen - create "Paste" button and enable on wizard

---

gossip-bin/src/ui/widgets/relay_entry.rs
gossip-lib/src/storage/types/relay2.rs

Relay Entry: Add Permission settings to relay edit view

---

gossip-bin/src/ui/feed/note/mod.rs
gossip-bin/src/ui/widgets/mod.rs

Fixes #645
There could be other places in the App affected by the egui change

Override mouse cursor on reaction labels.

---

gossip-bin/src/ui/mod.rs
gossip-bin/src/ui/widgets/mod.rs

Warn if no audio device is found when compiled with 'video-ffmpeg' option

---

gossip-bin/src/ui/feed/post.rs
gossip-bin/src/ui/mod.rs
gossip-bin/src/ui/people/person.rs
gossip-bin/src/ui/relays/known.rs
gossip-bin/src/ui/relays/mod.rs
gossip-bin/src/ui/settings/network.rs
gossip-bin/src/ui/you/metadata.rs

https://github.com/mikedilger/gossip/assets/3328670/3725f4a3-ca81-4c7e-b99e-653c7c8eefc1

Show relay list as clickable links that will go to relay configuration

---

gossip-bin/src/ui/feed/post.rs
gossip-bin/src/ui/widgets/contact_search.rs

Tagging: Do tag replacements only once per tag

---

gossip-bin/src/ui/mod.rs

- more cleaner and modular side_bar 
- more cleaner cap state detection
- fix typo

[REFACTOR] gossip-bin UI

---

gossip-bin/src/notedata.rs
gossip-bin/src/ui/dm_chat_list.rs
gossip-bin/src/ui/feed/mod.rs
gossip-bin/src/ui/feed/note/content.rs
gossip-bin/src/ui/feed/note/mod.rs
gossip-bin/src/ui/feed/post.rs
gossip-bin/src/ui/mod.rs
gossip-bin/src/ui/people/list.rs
gossip-bin/src/ui/people/person.rs
gossip-bin/src/ui/theme/test_page.rs
gossip-bin/src/ui/widgets/avatar.rs
gossip-bin/src/ui/widgets/mod.rs
gossip-bin/src/ui/widgets/modal_popup.rs
gossip-bin/src/ui/widgets/more_menu.rs

Re-Style DM note rendering by carefully refactoring note-rendering functions

DM Note Rendering

---

gossip-bin/src/ui/mod.rs
gossip-bin/src/ui/widgets/textedit.rs

Just a fine-tuning of textedit styles

Textedit styles

---

gossip-bin/src/ui/widgets/contact_search.rs

Fix scroll area that doesn't expand after shrinking.

---

packaging/flatpak/com.mikedilger.gossip.yml

This PR enhances the Flatpak packaging configuration by adding essential permissions for better user experience and performance.
- **Added `--filesystem=home` permission**: Allows users to easily browse and upload files from anywhere in their home directory
- **Added `--device=dri` permission**: Enables GPU hardware acceleration for improved graphics performance and smoother UI rendering
1. **File Access**: Without filesystem permissions, users would be restricted to very limited file access, making it difficult to upload files, avatars, or other content in Gossip
2. **Performance**: GPU acceleration provides:
- Smoother UI animations and transitions
- Better rendering performance for images and media
- Reduced CPU usage for graphics operations
- Overall improved user experience

Add filesystem and GPU access permissions to Flatpak manifest
