mikedilger/gossip

- Cargo.lock
- Cargo.toml
- src/tags.rs
- src/ui/feed.rs
For now, just formatting the text differently. 
As you can see, I am not a designer, so feel free to change this, but I kinda like it.
I am not sure it will be possible to actually rewrite it without causing glitches, but I also didn't try.
> Highlight npub/etc references in the textarea

- .github/workflows/build.yml
It builds for Linux, Mac and Windows and makes the binaries available for download. Includes caching builds.
See an example here: https://github.com/fiatjaf/gossip/actions/runs/3999588145
> github action to build every commit

- .github/workflows/build.yml
Basically all of the `actions-rs/*` actions are unmaintained. See <https://github.com/actions-rs/toolchain/issues/216> for more information. Due to their age they generate several warnings in CI runs, for example in https://github.com/mikedilger/gossip/actions/runs/4034307097:
> Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions-rs/toolchain@v1. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
To get rid of those warnings the `actions-rs/toolchain` is replaced by the newer `dtolnay/rust-toolchain`.
> Replace unmaintained actions-rs actions in CI workflows

- src/ui/feed/mod.rs
When pressing the "Raw" button in the "Feed" tab, display the JSON string with newlines and indentation, instead of the simple JSON string
> View raw notes as prettified JSON instead of a long JSON string

- .github/workflows/build.yml
Resolves #240.
Requires release branches to be named `releases/<something>`.
Review test workflow runs at https://github.com/0xbabo/gossip/actions.
> Build release branches

- src/feed.rs
- src/settings.rs
- src/ui/feed/mod.rs
- src/ui/help/mod.rs
- src/ui/mod.rs
- src/ui/settings.rs
And remove the "Include Replies in Following Feed" option from the settings
@mikedilger I suppose it is necessary to add a rollback migration to clean up the "replies_in_follows" key in the settings, but I don't know how to do it :)
> Split the Following section in Main feed and Conversations

- src/feed.rs
- src/settings.rs
- src/ui/feed/mod.rs
- src/ui/mod.rs
- src/ui/settings.rs
Inbox only includes direct replies and mentions, to summarize the most important notifications.
Activity monitors all the post where the user is tagged, sometimes "hell threads".
> Split Inbox section in Inbox and Activity

- src/ui/you/mod.rs
Now to access their notes the user has to find their own post, click on the user dropdown and click on the action "View...". This is an easy shortcut, the fact that it leads to the Feeds area (instead of creating a new Page type) is incidental but useful, because the user will then probably interact with other feeds.
> Add a You > Notes shortcut

- src/feed.rs
- src/overlord/mod.rs
Before:
- on startup, the main feed was loaded with a sort of stale state (2-3 days old messages)
- after almost exactly 7 seconds, the feed was updated with the latest events from the DB
This would happen even if recent feed events were already in the DB.
After:
- on startup, the main feed shows the latest events from the DB within 1-2s
Not sure exactly where the original 7s delay came from, but it was probably related to the 3.5s `DEFAULT_FEED_RECOMPUTE_INTERVAL_MS` and setting `Feed.last_computed` on initialization, even before any event was loaded.
> Recompute feed as soon as feed-related events are ready

- src/ui/mod.rs
- src/ui/search.rs
On PR #288 I introduced a stupid bug: the field is focused only the first time the page is viewed.
This fixes it, but I don't know if it is conceptually correct and set_inner_place is the right place.
I also renamed the variable to make clear his use and because this would be a bit a non-sense writing:
```rust
Page::Search => {
self.search_page = false;
}
```
> Fix search focus after first page view

- src/ui/feed/note/content.rs
While waiting for a correct management of images/videos it is probably useful to show a text placeholder instead of the complete url. Rationale: The image/video URL is rarely informative, often just confusing, with a standard placeholder when the user scans the content it can more easily identify external resources that are usually interesting information items. Hovering the placeholder provides the original URL, so the user can check it before clicking.
This could be useful even when there will be an option to show the images inline; if this option is off the user can click the placeholder to popup the image inside the main window.
Example:
> Show image / video placeholders instead of full urls

- src/comms.rs
- src/overlord/mod.rs
- src/ui/mod.rs
- src/ui/you/delegation.rs
Improvements to Delegation handling, see https://github.com/catenocrypt/gossip/issues/1
- Delete delegation too when identity is deleted, to prevent accidental preserving of wrong delegation
- Improved entry for delegation, separate showing of current and input of new
> Improvements to Delegation handling

- src/ui/theme/default.rs
Reduce the background contrast, compact the top and apply a proper padding.
@mikedilger let me know if you would like to add any tweaks to the dark version.
> Update the mention style in the Default theme

- src/ui/feed/note/content.rs
- src/ui/mod.rs
NIP-27 was merged a couple of days ago and specifies mentions and silent mentions using the `nostr:<NIP-19>` link type. Clients are starting to roll this out (Snort already has) so it makes sense to support at least "npub1", "nevent1" and "note1" for now.
Test note: note1a0g3ysxtnhszmraxcwlezzf9aaa9cfalj3r2g0nx97a9h7pj47zqr8s04m
> Implement nip 27

- src/settings.rs
- src/ui/mod.rs
- src/ui/settings.rs
- src/ui/theme/mod.rs
egui already automatically follows the OS dark-mode setting, but we don't handle it with our theme selection, resulting in messed up visuals. Now we check for this case and let the user decide whether to follow the OS or not.
> Add setting to follow OS dark-mode setting

- src/ui/feed/note/content.rs
The player keeps its threads running when paused, the threads get destroyed on stop. We will default to stopping the video instead of pausing.
> Quick fix for ffmpeg cpu hog

- src/ui/feed/post.rs
@mikedilger I tested this on unstable and then cherry picked on master because on unstable I have a newer db schema so master panics.
Please check it on Linux and let me know if ctrl is the desired key to activate the shortcut.
> Add cmd + enter shortcut to submit a post on macos

- src/ui/people/person.rs
Found out there is no way to copy npub of a profile into the clipboard b/c the text is not selectable and no copy button present. I've added a copy button.
> allow to copy a profile npub

- src/overlord/minion/mod.rs
Quick fix to make the logs more readable.
Fixes #434
> Keep only the first 10 output lines when unable to parse NIP-11

- src/ui/feed/note/mod.rs
As per subject, add command to share a note via njump: nostr.com/{nevent1xxxx}
> Add 'Copy web link' command for a note

- src/overlord/mod.rs
When pasting from e.g. signal-desktop, private keys can have a trailing newline that isn't readily visible. As a result the import mysteriously fails with a "Private key is not recognized" message.
This is fixed by trimming whitespace from the ends of keys before attempting to add them.
> trim keys before attempting import

- src/ui/feed/note/mod.rs
> Limit njump nevents to 3 relay hints to have a shorter URL

- gossip-bin/src/ui/feed/mod.rs
- gossip-bin/src/ui/help/mod.rs
- gossip-bin/src/ui/help/stats.rs
- gossip-bin/src/ui/help/theme.rs
- gossip-bin/src/ui/people/follow.rs
- gossip-bin/src/ui/relays/active.rs
- gossip-bin/src/ui/relays/known.rs
- gossip-bin/src/ui/relays/mine.rs
- gossip-bin/src/ui/search.rs
- gossip-bin/src/ui/settings/mod.rs
- gossip-bin/src/ui/you/delegation.rs
- gossip-bin/src/ui/you/metadata.rs
- gossip-bin/src/ui/you/mod.rs
I uniformed the view's title to have a coherent UI and avoid the flickering at the top, when switching areas.
I didn't touch the DM chat because it is under review in another branch, and the People one because it needs a complete makeover.
@bu5hm4nn I think  we need to build a layout/component to manage the basic view structure (title-header, body, scrolling); I will open an issue to track this.
> Uniform view's titles

- README.md
Formula was finally approved for `homebrew-core`!
For scoop this can be simplified with an official repository once my PR goes through eventually (https://github.com/ScoopInstaller/Extras/pull/11914)
> Install from brew/scoop

- README.md
Gossip is now in the `extras` bucket so we can simplify instructions for `scoop`.
> Update readme: scoop install from extras bucket

- gossip-bin/src/ui/settings/mod.rs
call `App::init_scaling()` after saving the settings because it reads the settings
> Fix bug when saving scaling settings

- gossip-bin/src/commands.rs
- gossip-bin/src/ui/wizard/follow_people.rs
- gossip-bin/src/ui/wizard/import_keys.rs
- gossip-bin/src/ui/wizard/import_private_key.rs
- gossip-bin/src/ui/wizard/import_public_key.rs
- gossip-bin/src/ui/wizard/mod.rs
- gossip-bin/src/ui/wizard/read_nostr_config.rs
- gossip-bin/src/ui/wizard/setup_metadata.rs
- gossip-bin/src/ui/wizard/setup_relays.rs
- gossip-bin/src/ui/wizard/welcome_gossip.rs
- gossip-bin/src/ui/wizard/welcome_nostr.rs
- gossip-bin/src/ui/wizard/wizard_state.rs
- gossip-lib/src/gossip_identity.rs
- gossip-lib/src/overlord/mod.rs
Most importantly this branch includes the fix to make feeds work immediately after completing the wizard without restarting the app.
But it also turned into a streamline rework of the onboarding process ahead of @dtonon complete design review. Below are screen recordings of all 4 onboarding paths for easy review:
https://github.com/mikedilger/gossip/assets/3328670/f58ff272-480b-4b3e-b8ec-b6a4bd6c2a7c
https://github.com/mikedilger/gossip/assets/3328670/964de25d-0a13-435b-bbc4-bd5ce50d37f9
https://github.com/mikedilger/gossip/assets/3328670/5c5b0069-74e6-4770-8069-1ac04a4559ae
https://github.com/mikedilger/gossip/assets/3328670/5fd74187-00bc-4617-a52e-58e1c26e65bb
> Streamline onboarding wizard

- gossip-bin/src/ui/feed/mod.rs
@dtonon please see the commit in this branch to see where to adjust the right margin
> Add right margin to the feed to make space for the scroll bar

- gossip-bin/src/ui/settings/ui.rs
(and dynamically adjust the slider) fixes #691
> Settings: Allow custom Mouse acceleration values in textbox 

- gossip-bin/src/ui/mod.rs
fixes #747; The message on the data migartion page is horizontaly and vertically centered.
> Nicer data migration page

- flake.lock
- flake.nix
This is a simplified [nix flake](https://nixos.wiki/wiki/Flakes) to create a reproducible dev environment across systems (including m2 macs) for gossip.
Uses [flakebox](https://github.com/rustshop/flakebox) for cross compilation but suppresses the flakebox inits for adding any of the workflows, formatting, and git fanciness.
If you've never used nix, the best installer is determinate systems (comes with flakes, commands, and better mac support):
```
curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix | sh -s -- install
```
or the normal nix installer at https://nixos.org/download/ (enable flakes and commands in the config)
If you have nix installed you'd just clone gossip down and run from the root directory
```
nix develop
```
and it'll install all the correct …
> feat: simple nix flake for developer environment

- gossip-bin/src/ui/mod.rs
This is the result in dark mode:
and this is the light mode:
Uses 255*(2/3) as opacity instead of 255*(1/2)
fixes #728
> fix: opacity of add_post_icon to 2/3 for better visibility on light mode

- gossip-bin/src/ui/feed/note/mod.rs
Web sharing is a fairly common action to promote a note outside Nostr, and hiding it within a generic “Copy ID” menu is a shame.
> Move the web sharing outside the "copy ID" menu

- gossip-lib/src/profile.rs
When the system tries to create the configuration directories, it crashes if it fails (say because of regular file there or a broken symlink). The out put is "File Exists" which makes troubleshooting difficult.
With this change, gossip prints the full path of the problematic file so the user khows where to look.
fixes #856
> Shows full path in case of a File Exists error

- gossip-bin/src/ui/relays/active.rs
- gossip-bin/src/ui/relays/known.rs
- gossip-bin/src/ui/relays/mine.rs
Its done by replacing
`widgets::page_header(ui, Page::RelaysActivityMonitor.name(), |ui|`
with
`widgets::page_header(ui, &format!("{} ({} relays)", Page::RelaysMine.name(), get_relays(app).len()), |ui| {`
on relay pages but diff is longer because of linting.
closes #306
> UI - Adding the number of relays to the configure relay pages

- gossip-bin/src/ui/people/list.rs
This addresses issue #975.
The tradeoff is that the contact tooltip will not disappear when the user clicks outside of the text box. However, this is what already happens in the post area.
> Prevent clearing search results when search box loses focus

- gossip-bin/src/ui/feed/note/content/media.rs
- gossip-bin/src/ui/feed/note/content/mod.rs
- gossip-bin/src/ui/feed/note/mod.rs
- gossip-bin/src/ui/help/about.rs
- gossip-bin/src/ui/mod.rs
- gossip-bin/src/ui/people/person.rs
- gossip-bin/src/ui/theme/test_page.rs
- gossip-bin/src/ui/widgets/link_context_menu.rs
- gossip-bin/src/ui/widgets/mod.rs
- gossip-lib/src/media.rs
Related issue: #878
While doing this I discovered that the "Retry loading" button on media links was not working.
> Add feature: right-click to copy link
